# Generated by Django 3.1.4 on 2021-01-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thimble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thimble',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
