# Generated by Django 3.1.4 on 2021-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thimble', '0002_thimble_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(choices=[('Обычный', 'Обычный')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='thimble',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
