# Generated by Django 3.1.4 on 2021-07-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thimble', '0004_auto_20210703_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(choices=[('Центральный фед.округ', 'Центральный фед.округ'), ('Северо-западный', 'Северо-западный'), ('Северный кавказ', 'Северный кавказ'), ('Южный', 'Южный'), ('Крым', 'Крым'), ('Приволжский', 'Приволжский'), ('Уральский', 'Уральский'), ('Сибирский', 'Сибирский'), ('Центральный фед.округ', 'Центральный фед.округ'), ('Иностранный', 'Иностранный')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(choices=[('Север Европы', 'Север Европы'), ('бывшие сов. республики', 'бывшие сов.республики'), ('Ближний Восток', 'Ближний Восток'), ('Африка', 'Африка'), ('Северная Америка', 'Северная Америка'), ('Южная Америка', 'Южная Америка')], max_length=200),
        ),
        migrations.AlterField(
            model_name='thimble',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='thimble.city'),
        ),
    ]
