# Generated by Django 3.1.4 on 2021-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thimble', '0006_city_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thimble',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='date',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='seria',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='shelf',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='stellaj',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='where',
        ),
        migrations.RemoveField(
            model_name='thimble',
            name='who_present',
        ),
        migrations.AlterField(
            model_name='thimble',
            name='type',
            field=models.CharField(choices=[('Обычный', 'Обычный'), ('Рабочий', 'Рабочий'), ('Сувенирный', 'Сувенирный'), ('Коллекционный', 'Коллекционные')], max_length=200),
        ),
    ]
